GET http://localhost:5215/games

###
GET http://localhost:5215/games/3

###
POST http://localhost:5215/games
Content-Type: application/json

{
  "name": "Hyeji's game",
  "genreId": 5,
  "price": 29.99,
  "releaseDate": "2023-07-15"
}

###
PUT http://localhost:5215/games/3
Content-Type: application/json

{
    "name": "Block Builder Pro!!",
    "genreId": 5,
    "price": 59.99,
    "releaseDate": "2024-03-11"
  }

###
DELETE http://localhost:5215/games/3